url: "https://uva-math.github.io"

name: Mathematics at the University of Virginia
description: Official website of Department of Mathematics at the University of Virginia (under construction)

markdown: kramdown
highlighter: rouge

excerpt_separator: <!--more-->

paginate: 10
paginate_path: "blog/page:num"
permalink: /:year/:month/:day/:title/

new_seminars_label: Upcoming seminars

defaults:
  - scope:
      path: ""
      type: departmentpeople
    values:
      layout: departmentpeople_page

collections:
  departmentpeople:
    output: true
    permalink: /people/:name

exclude: [vendor]
